# Get SSH Keys
- name: Get DigitalOcean SSH Keys
  digital_ocean_sshkey_info:
  environment:
    DO_API_TOKEN: "{{ do_api_token }}"
  register: ssh_keys

- set_fact:
    public_keys: "{{ public_keys + [item.public_key] }}"
    public_keys_id: "{{ public_keys_id + [item.id] }}"
  with_items: "{{ ssh_keys.data }}"

# Create DigitalOcean Droplet
- name: Create DigitalOcean Droplets
  digital_ocean_droplet:
    unique_name: yes
    state: present
    name: "do-{{ item.do_droplet_region }}-{{ item.do_droplet_name }}"
    size: "{{ item.do_droplet_size }}"
    region: "{{ item.do_droplet_region }}"
    image: "{{ item.do_droplet_image }}"
    private_networking: yes
    tags: ["server", "{{ item.do_droplet_region }}"]
    ssh_keys: "{{ public_keys_id }}"
  environment:
    DO_API_TOKEN: "{{ do_api_token }}"
  register: do_droplets
  with_items: "{{ droplets }}"

- name: Add IP to Hosts
  add_host:
    name: "{{ item.data.ip_address }}"
    groups: "web_server"
  with_items: "{{ do_droplets.results }}"